/**
 * String constants
 */
const strings = {
    appName: 'Hyperledger Fabric Client',
    navIdentities: 'Identities',
    navChaincodes: 'Chaincodes',
    headerIdentities: 'Create identities',
    headerChaincodes: 'Interact with chaincode',
    labelAdmin: 'Admin',
    labelClient: 'Client',
    labelPeer: 'Peer',
    labelOrderer: 'Orderer',
    labelIdentityRole: 'Identity role',
    labelRegisterEnroll: 'Register & Enroll',
    labelRegister: 'Register',
    labelEnroll: 'Enroll',
    labelEnrollmentProfile: 'Enrollment profile',
    labelDefault: 'Default',
    labelTls: 'TLS',
    labelAction: 'Action',
    labelQuery: 'Query',
    labelInvoke: 'Invoke',
    labelTransactionType: 'Transaction type',
    labelIdentity: 'Identity',
    labelChannelName: 'Channel name',
    labelChaincodeName: 'Chaincode name',
    labelFunctionName: 'Function name',
    labelArguments: 'Arguments (comma-separated values)',
    labelIdentityName: 'Identity name',
    labelIdentitySecret: 'Identity secret',
    labelEnrollAdmin: 'Enroll admin',
    labelSubmit: 'Submit',
    labelReturn: 'Return',
    labelClearWallet: 'Clear wallet',
    labelSuccessRegEnroll: 'Successfully registered and enrolled identity',
    labelSuccessRegister: 'Successfully registered identity',
    labelSuccessEnroll: 'Successfully enrolled identity',
    labelSuccessQuery: 'Successfully executed chaincode query:',
    labelSuccessInvoke: 'Successfully invoked chaincode function:',
    labelError: 'Error: Check client for error log',
    infoWalletEmpty: 'The wallet is empty',
    infoEnrollFirst: 'You must enroll an identity before interacting with the chaincode',
};

export default strings;
